services:
  - type: web
    name: iot-visualization
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      mkdir -p static templates &&
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port ${PORT:-10000} --workers 2 --timeout-keep-alive 30
    envVars:
      - key: MONGO_URI
        fromGroup: mongo_prod
    healthCheckPath: /health
    autoDeploy: true
    plan: free