services:
  - type: web
    name: iot-visualization
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port ${PORT:-10000} --workers 2
    envVars:
      - key: MONGO_URI
        fromGroup: mongo_prod
    healthCheckPath: /
    autoDeploy: true
    plan: free